import { Metadata } from "next";
import { LegalShell, Section } from "../legal-shell";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms you agree to when using AI Alt-Text Generator.",
};

export default function TermsPage() {
  return (
    <LegalShell title="Terms of Service" updated="May 22, 2026">
      <p>
        These terms apply when you use AI Alt-Text Generator (&quot;the
        Service&quot;) at <code>alt-text-tool-seven.vercel.app</code>. By
        signing in, you agree to them.
      </p>

      <Section heading="What the Service does">
        <p>
          You upload an image and the Service returns a short text description
          intended to be used as alt text. The descriptions are generated by a
          third-party AI model (currently Google Gemini 2.5 Flash). The Service
          is provided as-is. The output may be wrong, incomplete, or
          inappropriate for your context — you are responsible for reading and
          editing it before publishing.
        </p>
      </Section>

      <Section heading="Your account">
        <p>
          You must be at least 13 years old to use the Service. You sign in
          using a Google account; you are responsible for keeping that account
          secure. You agree not to share your account, automate sign-ins, or
          create multiple accounts to bypass usage limits.
        </p>
      </Section>

      <Section heading="Acceptable use">
        <p>You agree not to use the Service to:</p>
        <ul className="list-disc pl-5 space-y-2">
          <li>Upload images you don&apos;t have the right to use.</li>
          <li>
            Upload content that is illegal, defamatory, harmful, or sexually
            explicit material involving minors.
          </li>
          <li>
            Reverse-engineer, scrape, or automate the Service to generate alt
            text at scale outside of our paid plans.
          </li>
          <li>
            Attempt to break the Service or extract its prompts, model
            details, or other operational data.
          </li>
        </ul>
        <p>
          We may suspend or terminate accounts that violate these rules without
          notice.
        </p>
      </Section>

      <Section heading="Pricing and payments">
        <p>
          Free tier: 3 alt-text generations per account per day, refilling at
          00:00 UTC. Paid: $9 (USD) for 500 generation credits, one-time
          purchase, no subscription. Credits do not expire.
        </p>
        <p>
          Payments are processed by Polar.sh, who acts as the Merchant of
          Record. Their terms apply to the transaction. The price you see at
          checkout may include taxes depending on your country.
        </p>
      </Section>

      <Section heading="Refunds">
        <p>
          If you bought credits and haven&apos;t used them yet, we&apos;ll
          refund them within 7 days of purchase. Email{" "}
          <a
            className="underline hover:text-zinc-900 dark:hover:text-zinc-100"
            href="mailto:shlokuprit@gmail.com"
          >
            shlokuprit@gmail.com
          </a>{" "}
          with your account email and order ID. Already-used credits are
          non-refundable.
        </p>
      </Section>

      <Section heading="Service availability">
        <p>
          We aim for the Service to be available 24/7, but it depends on
          third-party providers (Vercel, Supabase, Google Gemini, Polar) and
          may have downtime. We do not offer an uptime SLA. If the Service is
          unavailable for an extended period and you cannot use credits you
          paid for, contact us for a refund.
        </p>
      </Section>

      <Section heading="No warranty">
        <p>
          The Service is provided &quot;as is&quot;, without warranty of any
          kind. We do not guarantee that the alt text generated will be
          accurate, accessibility-compliant, or fit for any particular purpose.
          You agree to review every output before using it.
        </p>
      </Section>

      <Section heading="Limitation of liability">
        <p>
          To the maximum extent permitted by law, our liability to you for any
          claim related to the Service is limited to the amount you have paid
          us in the 12 months before the claim. We are not liable for
          consequential or indirect damages.
        </p>
      </Section>

      <Section heading="Governing law">
        <p>
          These terms are governed by the laws of India. Any disputes that
          can&apos;t be resolved by email will be subject to the jurisdiction
          of the courts in India.
        </p>
      </Section>

      <Section heading="Changes to these terms">
        <p>
          We may update these terms occasionally. Material changes will be
          announced on the home page and the &quot;last updated&quot; date at
          the top of this page will change. Continuing to use the Service
          after a change means you accept the new terms.
        </p>
      </Section>

      <Section heading="Contact">
        <p>
          Questions? Email{" "}
          <a
            className="underline hover:text-zinc-900 dark:hover:text-zinc-100"
            href="mailto:shlokuprit@gmail.com"
          >
            shlokuprit@gmail.com
          </a>
          .
        </p>
      </Section>
    </LegalShell>
  );
}
